### ISSUE TITLE
Edit-Command

### ISSUE THREAD

**Issue by kronn** [heaths/gh-label#5]
This is a nice and useful extension to the github-cli. 

I would like to see an edit or update-action which allows me to change the color, name, or description of a label. Just passing arguments for the fields I want to change and leaving the other unchanged seems like the simplest complete solution to me.

Sadly, I do not know `go`, so I just opened this issue

**Comment by heaths** [comment]
It's coming. :smile:. I've been doing some refactoring to make it easier. I also plan on `delete`, `import` (import a list of labels - non-destructive, but considering a switch to allow deleting labels not in the list - probably should at least list them), and something like `merge` to make 1 or more repos like another - something we do a lot for the Azure SDK.

**Comment by heaths** [comment]
@kronn the binary itself hasn't been updated because, combined, they are already ~24MB, git stores full snapshots, and binaries don't compress well. The CLI team is [discussing a long-term solution](https://github.com/cli/cli/issues/4194) and I'd like to see what they say first - including about my [short-term and general perf idea](https://github.com/cli/cli/issues/4194#issuecomment-912716097) before I push the binaries.

If you have [the Go toolset](https://golang.org) installed, once you run `gh extension update gh-label` you can cd into its directory and run `./build`.

**Comment by heaths** [comment]
With all the new commands I added, the total size of the builds/ directory is now 58MB. Even if I strip symbols it's still 51MB.

**Comment by kronn** [comment]
Wow, that is indeed a lot. When trying the command today, it downloaded the binary on demand. I am kinda curious how you solved it. 

Also, the merge sounds like a great idea. For hitobito, I want something like it. Right now, I am fixing the color codes and making on-demand additions to the labels. For this, gh-label is nice tooling. I'll keep an eye on your releases.

**Comment by heaths** [comment]
It tries to find the last tag, find a release for it, and download the release binary for the appropriate platform.
